# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCc < Formula
  desc "A git extension to help write conventional commits."
  homepage "https://github.com/skalt/git-cc"
  version "0.0.16"
  license "Indie Code Catalog Standard Deal >= 4.1"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SKalt/git-cc/releases/download/v0.0.16/git-cc_0.0.16_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9bf3f0249e37c67541c77eb3d2ba13274dc9be999b5a31536a86aa85703c495c"

      def install
        bin.install "git-cc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SKalt/git-cc/releases/download/v0.0.16/git-cc_0.0.16_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b70b21b42f022d3fa17de932e0ff5ec1cb2e20b18165bbed6e239ade23e4998b"

      def install
        bin.install "git-cc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SKalt/git-cc/releases/download/v0.0.16/git-cc_0.0.16_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4cf28f3ceb2c5bdee1e294241df4bc038e3ab907be1885308b97b5810139690c"

      def install
        bin.install "git-cc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/SKalt/git-cc/releases/download/v0.0.16/git-cc_0.0.16_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "98442e0d487a7383969ec0f62690fe00ecd49181db3f3ae277621f1b84302ca5"

      def install
        bin.install "git-cc"
      end
    end
  end

  test do
    system "#{bin}/git-cc --version"
  end
end
