# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCc < Formula
  desc "A git extension to help write conventional commits."
  homepage "https://github.com/skalt/git-cc"
  version "0.2.5"
  license "Polyform-Free-Trial-1.0.0 OR Polyform-Noncommercial-1.0.0 OR COMMERCIAL"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/SKalt/git-cc/releases/download/v0.2.5/git-cc_0.2.5_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "8591d79fd28f742511210fcd381f6313a4566661e5ad4a2074c80aafd2e66f54"

      def install
        bin.install "git-cc"
      end
    end
    on_arm do
      url "https://github.com/SKalt/git-cc/releases/download/v0.2.5/git-cc_0.2.5_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "596a85285dc7a9edf64cc2ce63bd9ac94baa573ffc17a500b9a5b2c7b788abdd"

      def install
        bin.install "git-cc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SKalt/git-cc/releases/download/v0.2.5/git-cc_0.2.5_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "e74f9243261fe9b2fb5ec77219cd719db3617b9da1358722cb586a032a1ee625"

        def install
          bin.install "git-cc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SKalt/git-cc/releases/download/v0.2.5/git-cc_0.2.5_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "882bb8f5725b4136448f29498a574df8c371e61fc68b60610baf6269b49dcaf5"

        def install
          bin.install "git-cc"
        end
      end
    end
  end

  test do
    system "#{bin}/git-cc --version"
  end
end
