# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitCc < Formula
  desc "A git extension to help write conventional commits."
  homepage "https://github.com/skalt/git-cc"
  version "0.2.0"
  license "Indie Code Catalog Standard Deal >= 4.1"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/SKalt/git-cc/releases/download/v0.2.0/git-cc_0.2.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "6067ff0c24e7077cbe7a73fd3540e194e3a1cd62395ad98b34cb3de27c07f53b"

      def install
        bin.install "git-cc"
      end
    end
    on_arm do
      url "https://github.com/SKalt/git-cc/releases/download/v0.2.0/git-cc_0.2.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b72130ba9a1769a964a94b3bda670b25ec01774af421e5d18aaa11ef1497ddb8"

      def install
        bin.install "git-cc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SKalt/git-cc/releases/download/v0.2.0/git-cc_0.2.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "cffc431a64571367ac79c8757b4336dcdf6941d2bf628747e14c81ceb3353e71"

        def install
          bin.install "git-cc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/SKalt/git-cc/releases/download/v0.2.0/git-cc_0.2.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "5c079f1a2123e24cf87c7d13314de8a91c01586d60fbf915b3e9a121d23b8aab"

        def install
          bin.install "git-cc"
        end
      end
    end
  end

  test do
    system "#{bin}/git-cc --version"
  end
end
